import json

COMPONENT_REGISTRY_LIST = [
    # 1. Executive Decision Widgets
    {"name": "ExecutiveHero", "domain": "Executive", "purpose": "High-level identity and quick summary", "typical_data": ["profile.name", "profile.overview"]},
    {"name": "CompanyIdentityCard", "domain": "Executive", "purpose": "Company core info", "typical_data": ["profile.headquarters", "profile.employee_count"]},
    {"name": "ExecutiveHeadline", "domain": "Executive", "purpose": "Main headline takeaway", "typical_data": ["draft_report.executive_summary"]},
    {"name": "ExecutiveVerdictCard", "domain": "Executive", "purpose": "Final verdict on the company", "typical_data": ["draft_report.recommendations"]},
    {"name": "DecisionBanner", "domain": "Executive", "purpose": "Call to action or decision required", "typical_data": []},
    {"name": "KeyTakeawaysStrip", "domain": "Executive", "purpose": "Horizontal strip of 3-4 key points", "typical_data": ["draft_report.key_findings"]},
    {"name": "ExecutiveScorecard", "domain": "Executive", "purpose": "High-level scorecard of performance", "typical_data": ["analytics.cagr"]},
    {"name": "NorthStarMetrics", "domain": "Executive", "purpose": "The 1-2 most important metrics", "typical_data": ["financials.revenue_history"]},
    {"name": "BusinessHealthIndicator", "domain": "Executive", "purpose": "Overall health gauge", "typical_data": ["financials.net_income_history"]},
    {"name": "ConfidenceMeter", "domain": "Executive", "purpose": "Confidence level in the assessment", "typical_data": ["entity.metadata.confidence"]},
    {"name": "CoverageMeter", "domain": "Executive", "purpose": "Data coverage indicator", "typical_data": []},
    {"name": "EvidenceQualityCard", "domain": "Executive", "purpose": "Summary of evidence quality", "typical_data": []},

    # 2. KPI & Performance Widgets
    {"name": "KpiTile", "domain": "KPI", "purpose": "Single KPI block", "typical_data": []},
    {"name": "KpiGrid", "domain": "KPI", "purpose": "Grid of multiple KPIs", "typical_data": []},
    {"name": "KpiComparison", "domain": "KPI", "purpose": "Compare KPI against peers", "typical_data": []},
    {"name": "MetricStrip", "domain": "KPI", "purpose": "Horizontal row of metrics", "typical_data": []},
    {"name": "MetricTrendCard", "domain": "KPI", "purpose": "Metric with a small trendline", "typical_data": []},
    {"name": "MetricSparkline", "domain": "KPI", "purpose": "Metric with sparkline chart", "typical_data": []},
    {"name": "BenchmarkCard", "domain": "KPI", "purpose": "Performance vs benchmark", "typical_data": []},
    {"name": "VarianceCard", "domain": "KPI", "purpose": "Budget or expected variance", "typical_data": []},
    {"name": "CAGRCard", "domain": "KPI", "purpose": "Compound annual growth rate display", "typical_data": ["analytics.cagr"]},
    {"name": "GrowthIndicator", "domain": "KPI", "purpose": "Growth % display", "typical_data": ["analytics.revenue_growth"]},
    {"name": "MarginCard", "domain": "KPI", "purpose": "Profit margins", "typical_data": ["analytics.operating_margin"]},
    {"name": "EfficiencyCard", "domain": "KPI", "purpose": "Efficiency metrics", "typical_data": []},
    {"name": "CashFlowCard", "domain": "KPI", "purpose": "Cash flow summary", "typical_data": ["financials.cash_flow_history"]},
    {"name": "ProfitabilityCard", "domain": "KPI", "purpose": "Profitability summary", "typical_data": ["financials.net_income_history"]},
    {"name": "UtilizationCard", "domain": "KPI", "purpose": "Resource or capacity utilization", "typical_data": []},

    # 3. Financial Intelligence Widgets
    {"name": "RevenueLineChart", "domain": "Financial", "purpose": "Revenue trend over time", "typical_data": ["financials.revenue_history"]},
    {"name": "EBITDAChart", "domain": "Financial", "purpose": "EBITDA trend", "typical_data": []},
    {"name": "EPSChart", "domain": "Financial", "purpose": "Earnings per share trend", "typical_data": []},
    {"name": "OperatingMarginChart", "domain": "Financial", "purpose": "Operating margin trend", "typical_data": ["analytics.operating_margin"]},
    {"name": "FreeCashFlowChart", "domain": "Financial", "purpose": "Free cash flow trend", "typical_data": ["financials.cash_flow_history"]},
    {"name": "DebtTrendChart", "domain": "Financial", "purpose": "Debt over time", "typical_data": ["financials.long_term_debt_history"]},
    {"name": "WorkingCapitalChart", "domain": "Financial", "purpose": "Working capital trend", "typical_data": []},
    {"name": "CapexTrend", "domain": "Financial", "purpose": "Capital expenditures trend", "typical_data": ["capital_allocation.capex_trend"]},
    {"name": "DividendHistory", "domain": "Financial", "purpose": "Dividends paid over time", "typical_data": ["capital_allocation.dividends"]},
    {"name": "BuybackHistory", "domain": "Financial", "purpose": "Stock buybacks over time", "typical_data": ["capital_allocation.buybacks"]},
    {"name": "WaterfallAnalysis", "domain": "Financial", "purpose": "Revenue to profit bridge", "typical_data": ["financials.revenue_history", "financials.net_income_history"]},
    {"name": "SankeyCashFlow", "domain": "Financial", "purpose": "Cash flow in and out", "typical_data": []},
    {"name": "FinancialHeatmap", "domain": "Financial", "purpose": "Heatmap of financial health", "typical_data": []},
    {"name": "RatioRadarChart", "domain": "Financial", "purpose": "Radar chart of financial ratios", "typical_data": []},
    {"name": "MultiMetricTrend", "domain": "Financial", "purpose": "Multiple metrics on one chart", "typical_data": []},
    {"name": "FinancialStatement", "domain": "Financial", "purpose": "Tabular financial statement", "typical_data": ["financials.revenue_history", "financials.net_income_history"]},
    {"name": "RatioTable", "domain": "Financial", "purpose": "Table of financial ratios", "typical_data": []},
    {"name": "ValuationMultiples", "domain": "Financial", "purpose": "Valuation metrics table", "typical_data": ["valuation_multiples.pe_ratio"]},
    {"name": "DCFSummary", "domain": "Financial", "purpose": "Discounted cash flow summary", "typical_data": []},
    {"name": "EarningsBridge", "domain": "Financial", "purpose": "Earnings bridge analysis", "typical_data": []},
    {"name": "SegmentRevenueTable", "domain": "Financial", "purpose": "Revenue by segment", "typical_data": []},

    # 4. Strategy Consulting Widgets
    {"name": "SWOTGrid", "domain": "Strategy", "purpose": "2x2 SWOT analysis", "typical_data": ["swot.strengths", "swot.weaknesses"]},
    {"name": "TOWSMatrix", "domain": "Strategy", "purpose": "TOWS strategy matrix", "typical_data": []},
    {"name": "PESTLEGrid", "domain": "Strategy", "purpose": "Macro-environmental factors", "typical_data": []},
    {"name": "PorterFiveForces", "domain": "Strategy", "purpose": "Porter's industry analysis", "typical_data": []},
    {"name": "BCGMatrix", "domain": "Strategy", "purpose": "Growth-share matrix", "typical_data": []},
    {"name": "GEMcKinseyMatrix", "domain": "Strategy", "purpose": "Industry attractiveness vs competitive strength", "typical_data": []},
    {"name": "AnsoffMatrix", "domain": "Strategy", "purpose": "Product/Market growth matrix", "typical_data": []},
    {"name": "ValueChainDiagram", "domain": "Strategy", "purpose": "Value chain analysis", "typical_data": []},
    {"name": "BusinessModelCanvas", "domain": "Strategy", "purpose": "Business model components", "typical_data": []},
    {"name": "VRIOMatrix", "domain": "Strategy", "purpose": "Resource capability analysis", "typical_data": []},
    {"name": "CoreCompetencyMap", "domain": "Strategy", "purpose": "Core competencies map", "typical_data": []},
    {"name": "CapabilityAssessment", "domain": "Strategy", "purpose": "Assessment of organizational capabilities", "typical_data": []},
    {"name": "StrategicThemes", "domain": "Strategy", "purpose": "Key strategic themes", "typical_data": ["industry_context.strategic_themes"]},
    {"name": "TransformationRoadmap", "domain": "Strategy", "purpose": "Long term strategic roadmap", "typical_data": []},

    # 5. Market Intelligence Widgets
    {"name": "MarketSizeCard", "domain": "Market", "purpose": "Overall market size", "typical_data": []},
    {"name": "TAMSAMSOM", "domain": "Market", "purpose": "Market sizing breakdown", "typical_data": []},
    {"name": "IndustryLifecycle", "domain": "Market", "purpose": "Position in lifecycle", "typical_data": []},
    {"name": "IndustryGrowthCurve", "domain": "Market", "purpose": "Market growth projection", "typical_data": []},
    {"name": "ValueChainLandscape", "domain": "Market", "purpose": "Industry value chain", "typical_data": []},
    {"name": "EcosystemMap", "domain": "Market", "purpose": "Industry ecosystem players", "typical_data": []},
    {"name": "PorterMap", "domain": "Market", "purpose": "Porter's 5 forces map", "typical_data": []},
    {"name": "RegulationTimeline", "domain": "Market", "purpose": "Timeline of regulatory events", "typical_data": []},
    {"name": "MarketShareDonut", "domain": "Market", "purpose": "Market share pie/donut", "typical_data": ["competitive_positioning.market_share_estimate"]},
    {"name": "MarketShareBar", "domain": "Market", "purpose": "Market share bar chart", "typical_data": ["competitive_positioning.market_share_estimate"]},
    {"name": "GeographicExpansion", "domain": "Market", "purpose": "Map of geographic presence", "typical_data": []},
    {"name": "IndustryBenchmark", "domain": "Market", "purpose": "Comparison against industry averages", "typical_data": []},

    # 6. Competitive Intelligence
    {"name": "CompetitiveMatrix", "domain": "Competitive", "purpose": "Side-by-side competitor comparison", "typical_data": ["competitors"]},
    {"name": "FeatureComparison", "domain": "Competitive", "purpose": "Product feature checkmarks", "typical_data": []},
    {"name": "PricingComparison", "domain": "Competitive", "purpose": "Pricing tiers vs competitors", "typical_data": []},
    {"name": "PositioningMap", "domain": "Competitive", "purpose": "2-axis scatter of competitors", "typical_data": ["competitive_positioning.axes"]},
    {"name": "BrandPerceptionMatrix", "domain": "Competitive", "purpose": "Brand perception mapping", "typical_data": []},
    {"name": "CompetitiveRadar", "domain": "Competitive", "purpose": "Radar chart of capabilities vs peers", "typical_data": []},
    {"name": "CapabilityComparison", "domain": "Competitive", "purpose": "Comparison of capabilities", "typical_data": []},
    {"name": "ProductComparison", "domain": "Competitive", "purpose": "Product vs Product analysis", "typical_data": []},
    {"name": "WinLossAnalysis", "domain": "Competitive", "purpose": "Win/Loss rates vs competitor", "typical_data": []},
    {"name": "WhiteSpaceMap", "domain": "Competitive", "purpose": "Market gaps / whitespace", "typical_data": []},
    {"name": "CompetitiveMoat", "domain": "Competitive", "purpose": "Analysis of defensibility", "typical_data": []},

    # 7. Customer Intelligence
    {"name": "PersonaCards", "domain": "Customer", "purpose": "Target customer profiles", "typical_data": []},
    {"name": "JourneyMap", "domain": "Customer", "purpose": "Customer journey stages", "typical_data": []},
    {"name": "ExperienceMap", "domain": "Customer", "purpose": "Customer experience mapping", "typical_data": []},
    {"name": "Funnel", "domain": "Customer", "purpose": "Conversion funnel", "typical_data": []},
    {"name": "RetentionCurve", "domain": "Customer", "purpose": "Cohort retention over time", "typical_data": []},
    {"name": "ChurnAnalysis", "domain": "Customer", "purpose": "Churn rate and reasons", "typical_data": []},
    {"name": "NPSGauge", "domain": "Customer", "purpose": "Net Promoter Score", "typical_data": []},
    {"name": "VoiceOfCustomer", "domain": "Customer", "purpose": "Customer quotes and sentiment", "typical_data": []},
    {"name": "CustomerPainMatrix", "domain": "Customer", "purpose": "Pain points mapped to severity", "typical_data": []},
    {"name": "JTBDMap", "domain": "Customer", "purpose": "Jobs To Be Done mapping", "typical_data": []},
    {"name": "SegmentTree", "domain": "Customer", "purpose": "Customer segmentation breakdown", "typical_data": []},
    {"name": "FeatureRequests", "domain": "Customer", "purpose": "Top requested features", "typical_data": []},
    {"name": "SatisfactionHeatmap", "domain": "Customer", "purpose": "CSAT by feature or stage", "typical_data": []},

    # 8. Marketing Intelligence
    {"name": "BrandHealth", "domain": "Marketing", "purpose": "Overall brand metrics", "typical_data": []},
    {"name": "BrandEquityRadar", "domain": "Marketing", "purpose": "Brand equity components", "typical_data": []},
    {"name": "AwarenessFunnel", "domain": "Marketing", "purpose": "Brand awareness to loyalty", "typical_data": []},
    {"name": "MarketingMix7P", "domain": "Marketing", "purpose": "7Ps of marketing", "typical_data": []},
    {"name": "STPFramework", "domain": "Marketing", "purpose": "Segmentation, Targeting, Positioning", "typical_data": []},
    {"name": "CampaignPerformance", "domain": "Marketing", "purpose": "Ad/Campaign ROI", "typical_data": []},
    {"name": "ChannelMix", "domain": "Marketing", "purpose": "Acquisition channels", "typical_data": []},
    {"name": "SocialReach", "domain": "Marketing", "purpose": "Social media metrics", "typical_data": []},
    {"name": "EngagementTimeline", "domain": "Marketing", "purpose": "User engagement over time", "typical_data": []},
    {"name": "ShareOfVoice", "domain": "Marketing", "purpose": "Brand mentions vs competitors", "typical_data": []},
    {"name": "InfluencerNetwork", "domain": "Marketing", "purpose": "Influencer map", "typical_data": []},
    {"name": "SEOComparison", "domain": "Marketing", "purpose": "Search engine visibility", "typical_data": []},

    # 9. Technology Intelligence
    {"name": "TechStackBadges", "domain": "Technology", "purpose": "Logos of software used", "typical_data": ["technology_stack"]},
    {"name": "CloudArchitecture", "domain": "Technology", "purpose": "Cloud setup diagram", "typical_data": []},
    {"name": "AIReadiness", "domain": "Technology", "purpose": "AI maturity assessment", "typical_data": []},
    {"name": "PatentTimeline", "domain": "Technology", "purpose": "Patents filed over time", "typical_data": []},
    {"name": "DeveloperActivity", "domain": "Technology", "purpose": "Code commits/releases", "typical_data": []},
    {"name": "GitHubHeatmap", "domain": "Technology", "purpose": "Git commit heatmap", "typical_data": []},
    {"name": "HiringSignals", "domain": "Technology", "purpose": "Tech roles being hired", "typical_data": ["hiring_signals"]},
    {"name": "EngineeringVelocity", "domain": "Technology", "purpose": "Sprint velocity / output", "typical_data": []},
    {"name": "ArchitectureDiagram", "domain": "Technology", "purpose": "System architecture", "typical_data": []},
    {"name": "DependencyGraph", "domain": "Technology", "purpose": "System dependencies", "typical_data": []},
    {"name": "ModernizationScore", "domain": "Technology", "purpose": "Tech debt / modernization index", "typical_data": []},

    # 10. Risk Intelligence
    {"name": "RiskMatrix", "domain": "Risk", "purpose": "Impact vs Likelihood scatter", "typical_data": ["risk_factors"]},
    {"name": "RiskHeatmap", "domain": "Risk", "purpose": "Grid of risk areas", "typical_data": ["risk_factors"]},
    {"name": "RiskRegister", "domain": "Risk", "purpose": "Table of identified risks", "typical_data": ["risk_factors"]},
    {"name": "ScenarioAnalysis", "domain": "Risk", "purpose": "Best/Base/Worst case scenarios", "typical_data": []},
    {"name": "MonteCarloSummary", "domain": "Risk", "purpose": "Probability distribution", "typical_data": []},
    {"name": "StressTest", "domain": "Risk", "purpose": "Performance under stress", "typical_data": []},
    {"name": "RiskTrend", "domain": "Risk", "purpose": "Risk exposure over time", "typical_data": []},
    {"name": "MitigationTracker", "domain": "Risk", "purpose": "Status of risk mitigations", "typical_data": []},
    {"name": "RegulatoryTimeline", "domain": "Risk", "purpose": "Upcoming regulations", "typical_data": []},
    {"name": "ComplianceDashboard", "domain": "Risk", "purpose": "Compliance metrics", "typical_data": []},

    # 11. M&A / Investment Widgets
    {"name": "InvestmentScorecard", "domain": "Investment", "purpose": "Overall investment rating", "typical_data": []},
    {"name": "AcquisitionTimeline", "domain": "Investment", "purpose": "History of M&A", "typical_data": []},
    {"name": "SynergyMap", "domain": "Investment", "purpose": "Expected deal synergies", "typical_data": []},
    {"name": "OwnershipTree", "domain": "Investment", "purpose": "Corporate structure", "typical_data": []},
    {"name": "ShareholdingChart", "domain": "Investment", "purpose": "Major shareholders", "typical_data": []},
    {"name": "CapitalStructure", "domain": "Investment", "purpose": "Debt vs Equity mix", "typical_data": []},
    {"name": "DealComparison", "domain": "Investment", "purpose": "Precedent transactions", "typical_data": []},
    {"name": "ValuationBridge", "domain": "Investment", "purpose": "Bridge from standalone to post-deal value", "typical_data": []},
    {"name": "ReturnSensitivity", "domain": "Investment", "purpose": "IRR sensitivity table", "typical_data": []},
    {"name": "ExitScenario", "domain": "Investment", "purpose": "Potential exit routes", "typical_data": []},

    # 12. ESG Widgets
    {"name": "ESGScorecard", "domain": "ESG", "purpose": "Environmental, Social, Governance rating", "typical_data": []},
    {"name": "CarbonDashboard", "domain": "ESG", "purpose": "Emissions tracking", "typical_data": []},
    {"name": "GovernanceStructure", "domain": "ESG", "purpose": "Board composition and rules", "typical_data": []},
    {"name": "DiversityDashboard", "domain": "ESG", "purpose": "DEI metrics", "typical_data": []},
    {"name": "SustainabilityGoals", "domain": "ESG", "purpose": "Progress towards net zero etc.", "typical_data": []},
    {"name": "SDGAlignment", "domain": "ESG", "purpose": "Alignment with UN SDGs", "typical_data": []},
    {"name": "ESGTrend", "domain": "ESG", "purpose": "Improvement in ESG scores", "typical_data": []},

    # 13. Operations
    {"name": "SupplyChainMap", "domain": "Operations", "purpose": "Map of suppliers/logistics", "typical_data": []},
    {"name": "FactoryMap", "domain": "Operations", "purpose": "Locations of facilities", "typical_data": []},
    {"name": "ProcessFlow", "domain": "Operations", "purpose": "Operational process diagram", "typical_data": []},
    {"name": "BottleneckDiagram", "domain": "Operations", "purpose": "System constraints", "typical_data": []},
    {"name": "CapacityUtilization", "domain": "Operations", "purpose": "Factory/System utilization %", "typical_data": []},
    {"name": "LeadTimeAnalysis", "domain": "Operations", "purpose": "Order to delivery time", "typical_data": []},
    {"name": "LogisticsFlow", "domain": "Operations", "purpose": "Shipping and distribution", "typical_data": []},
    {"name": "VendorRisk", "domain": "Operations", "purpose": "Supplier risk assessment", "typical_data": []},

    # 14. Organizational Intelligence
    {"name": "OrgChart", "domain": "Organization", "purpose": "Reporting structure", "typical_data": []},
    {"name": "LeadershipCards", "domain": "Organization", "purpose": "Key executive profiles", "typical_data": ["leadership"]},
    {"name": "BoardComposition", "domain": "Organization", "purpose": "Board of directors details", "typical_data": []},
    {"name": "SuccessionMap", "domain": "Organization", "purpose": "Succession planning", "typical_data": []},
    {"name": "HiringHeatmap", "domain": "Organization", "purpose": "Where/what roles are hiring", "typical_data": ["hiring_signals"]},
    {"name": "TalentPipeline", "domain": "Organization", "purpose": "Recruiting metrics", "typical_data": []},
    {"name": "SkillsMatrix", "domain": "Organization", "purpose": "Employee capability gaps", "typical_data": []},

    # 15. News & External Intelligence
    {"name": "NewsTimeline", "domain": "External", "purpose": "Recent press coverage", "typical_data": ["news"]},
    {"name": "EventTimeline", "domain": "External", "purpose": "Key corporate events", "typical_data": []},
    {"name": "M&AEvents", "domain": "External", "purpose": "Recent acquisitions", "typical_data": []},
    {"name": "FundingTimeline", "domain": "External", "purpose": "Capital raises", "typical_data": []},
    {"name": "ProductLaunches", "domain": "External", "purpose": "New product releases", "typical_data": []},
    {"name": "LitigationTimeline", "domain": "External", "purpose": "Legal events", "typical_data": []},
    {"name": "RegulatoryEvents", "domain": "External", "purpose": "Compliance events", "typical_data": []},
    {"name": "SentimentTimeline", "domain": "External", "purpose": "Public sentiment over time", "typical_data": ["social_sentiment"]},

    # 16. Recommendation Widgets
    {"name": "InitiativeCards", "domain": "Recommendation", "purpose": "Proposed strategic initiatives", "typical_data": ["draft_report.recommendations"]},
    {"name": "PrioritizationMatrix", "domain": "Recommendation", "purpose": "Impact vs Effort", "typical_data": []},
    {"name": "ImpactEffort", "domain": "Recommendation", "purpose": "Impact vs Effort scatter", "typical_data": []},
    {"name": "DecisionTree", "domain": "Recommendation", "purpose": "Logic for making a choice", "typical_data": []},
    {"name": "Roadmap", "domain": "Recommendation", "purpose": "Gantt or timeline of actions", "typical_data": []},
    {"name": "OKRBoard", "domain": "Recommendation", "purpose": "Objectives and Key Results", "typical_data": []},
    {"name": "ActionTracker", "domain": "Recommendation", "purpose": "Next steps and owners", "typical_data": []},
    {"name": "ExecutiveChecklist", "domain": "Recommendation", "purpose": "Tasks for leadership", "typical_data": []},
    {"name": "Next90Days", "domain": "Recommendation", "purpose": "90-day execution plan", "typical_data": []},
    {"name": "ImplementationPlan", "domain": "Recommendation", "purpose": "Detailed rollout plan", "typical_data": []},

    # 17. Appendix Widgets
    {"name": "EvidenceTable", "domain": "Appendix", "purpose": "Raw data supporting claims", "typical_data": ["draft_report.key_findings"]},
    {"name": "SourceTable", "domain": "Appendix", "purpose": "List of URLs/Documents", "typical_data": []},
    {"name": "CitationCards", "domain": "Appendix", "purpose": "Specific quotes/excerpts", "typical_data": []},
    {"name": "MethodologyCard", "domain": "Appendix", "purpose": "How the report was made", "typical_data": []},
    {"name": "CoverageReport", "domain": "Appendix", "purpose": "What data was found vs missing", "typical_data": []},
    {"name": "DataQualityScore", "domain": "Appendix", "purpose": "Reliability of the data", "typical_data": []},
    {"name": "MissingEvidence", "domain": "Appendix", "purpose": "Identified data gaps", "typical_data": ["draft_report.evidence_gaps"]},
    {"name": "ConfidenceBreakdown", "domain": "Appendix", "purpose": "Confidence by section", "typical_data": []},

    # 18. Cross-Slide Executive Components
    {"name": "InsightCard", "domain": "Cross-Slide", "purpose": "Standalone key insight", "typical_data": ["draft_report.key_findings"]},
    {"name": "ExecutiveCallout", "domain": "Cross-Slide", "purpose": "Important note for CEO", "typical_data": []},
    {"name": "WarningBanner", "domain": "Cross-Slide", "purpose": "Red flag alert", "typical_data": ["draft_report.legacy_risks"]},
    {"name": "OpportunityBanner", "domain": "Cross-Slide", "purpose": "Green flag alert", "typical_data": ["draft_report.opportunities"]},
    {"name": "DecisionPoint", "domain": "Cross-Slide", "purpose": "A specific choice to make", "typical_data": []},
    {"name": "WhyItMatters", "domain": "Cross-Slide", "purpose": "Contextual explanation", "typical_data": []},
    {"name": "ExecutiveQuestion", "domain": "Cross-Slide", "purpose": "Posing a strategic question", "typical_data": []},
    {"name": "RecommendationHighlight", "domain": "Cross-Slide", "purpose": "Highlighted action", "typical_data": ["draft_report.recommendations"]},
    {"name": "BusinessImpact", "domain": "Cross-Slide", "purpose": "Financial or strategic impact", "typical_data": []},
    {"name": "ConfidenceIndicator", "domain": "Cross-Slide", "purpose": "Small badge for data confidence", "typical_data": []},

    # 19. Consulting Narrative Blocks
    {"name": "QuestionBlock", "domain": "Narrative", "purpose": "Poses the business question", "typical_data": []},
    {"name": "HypothesisBlock", "domain": "Narrative", "purpose": "States the initial theory", "typical_data": []},
    {"name": "EvidenceBlock", "domain": "Narrative", "purpose": "Presents the facts", "typical_data": ["draft_report.key_findings"]},
    {"name": "InsightBlock", "domain": "Narrative", "purpose": "Synthesizes the facts", "typical_data": []},
    {"name": "ImplicationBlock", "domain": "Narrative", "purpose": "What this means for the business", "typical_data": []},
    {"name": "RecommendationBlock", "domain": "Narrative", "purpose": "What to do about it", "typical_data": ["draft_report.recommendations"]},
    {"name": "ExecutiveSummaryBlock", "domain": "Narrative", "purpose": "Paragraph summary", "typical_data": ["draft_report.executive_summary"]},
    {"name": "SoWhatBlock", "domain": "Narrative", "purpose": "The ultimate takeaway", "typical_data": []},
    {"name": "WhyNowBlock", "domain": "Narrative", "purpose": "Urgency explanation", "typical_data": []},
    {"name": "KeyObservationBlock", "domain": "Narrative", "purpose": "Notable finding", "typical_data": []},
    {"name": "CounterEvidenceBlock", "domain": "Narrative", "purpose": "Data that contradicts the thesis", "typical_data": []},
    {"name": "StrategicImplicationBlock", "domain": "Narrative", "purpose": "Long term effect", "typical_data": []},
    {"name": "DecisionRequiredBlock", "domain": "Narrative", "purpose": "Prompt for executive decision", "typical_data": []},

    # 20. Interactive Executive Widgets
    {"name": "DrillDownPanel", "domain": "Interactive", "purpose": "Expandable details", "typical_data": []},
    {"name": "ExpandableEvidenceCard", "domain": "Interactive", "purpose": "Click to see sources", "typical_data": []},
    {"name": "LinkedChart", "domain": "Interactive", "purpose": "Chart tied to a data table", "typical_data": []},
    {"name": "ScenarioSlider", "domain": "Interactive", "purpose": "Interactive scenario modeler", "typical_data": []},
    {"name": "TimeTravelSlider", "domain": "Interactive", "purpose": "View historical snapshots", "typical_data": []},
    {"name": "PeerSelector", "domain": "Interactive", "purpose": "Dropdown to change competitor", "typical_data": []},
    {"name": "MetricComparisonToggle", "domain": "Interactive", "purpose": "Toggle absolute vs %", "typical_data": []},
    {"name": "GeographicFilter", "domain": "Interactive", "purpose": "Map filter", "typical_data": []},
    {"name": "BusinessUnitFilter", "domain": "Interactive", "purpose": "Segment filter", "typical_data": []},
    {"name": "EvidenceExplorer", "domain": "Interactive", "purpose": "Searchable evidence base", "typical_data": []},
    {"name": "KnowledgeGraphViewer", "domain": "Interactive", "purpose": "Node graph of entities", "typical_data": []},
    {"name": "RelationshipGraph", "domain": "Interactive", "purpose": "Connections map", "typical_data": []},
    {"name": "TimelineScrubber", "domain": "Interactive", "purpose": "Drag to see events", "typical_data": []}
]

COMPONENT_REGISTRY_JSON = json.dumps(COMPONENT_REGISTRY_LIST, indent=2)
